### PR TITLE
Migration stuff

### PR DESCRIPTION
**Pull request by TacoTheDank**
I tried my best, but, god, VSCode is weird and unnatural. I used Eclipse instead (installed for this purpose), except Eclipse provides literally nothing in debugging or lints to help. I tried to make this as error-free as possible, but something probably snuck in. This was painful. I apologize in advance for any debugging work you have to do because of this.

### 1st commit
- Delete 5 unneeded files

### 2nd commit
- Updated some dependencies

### 3rd commit
- Remove unused imports

### CODE REVIEW

**Comment by tobykurien** [comment]
Thank you so much for going to the effort, and sorry that it was painful. I hope that after the teething problems, you will get to experience the simpler (and in my opinion, beautiful) code that Xtendroid provides.

**Comment by tobykurien** [comment]
PS: if you need assistance or would like to chat to ask questions about the code or setup, feel fee to get in touch with me, I would be happy to assist. Details here: https://tobykurien.com/contact/

**Comment by tobykurien** [comment]
I am getting the following compile error (using openJDK 13.0.1):

```
* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > 'java.util.List com.android.build.gradle.api.BaseVariant.getOutputs()'
```

**Comment by TacoTheDank** [comment]
@tobykurien The .iml files and local.properties are automatically generated on everyone's computers when they open a project, so they aren't needed in Git.

The sample local.properties isn't exactly accurate, I think. It would look more like this:
```
## This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
#SUN-SAT MONTH DAY HH:MM:SS TIMEZONE YYYY
sdk.dir=C\:\\Users\\Sample\\AppData\\Local\\Android\\Sdk
```

**Comment by TacoTheDank** [comment]
> I am getting the following compile error (using openJDK 13.0.1):
> 
> ```
> * What went wrong:
> A problem occurred configuring project ':app'.
> > Failed to notify project evaluation listener.
>    > 'java.util.List com.android.build.gradle.api.BaseVariant.getOutputs()'
> ```

Yeah, that's an issue I've been getting. It seems to be an issue with a dependency or plugin: https://github.com/JakeWharton/butterknife/issues/1130
https://medium.com/@ErikJhordanRey/migrate-to-new-android-plugin-for-gradle-3-6790e79c5f3f

**Comment by tobykurien** [comment]
There's no butterknife in this project, however I can tell you that this is the reason I kept using older Gradle and gradle plugin versions. This is the kind of error that happens when the gradle version and plugin version don't match. Try going back to older versions of gradle till it works

**Comment by tobykurien** [comment]
PS: I get past that error if I revert the gradle version. Then I end up with:

```
Could not resolve com.google.guava:guava:27.1-jre.
     Required by:
         project : > com.android.tools.build:gradle:3.6.3 > com.android.tools.analytics-library:crash:26.6.3
         project : > com.android.tools.build:gradle:3.6.3 > com.android.tools.lint:lint-gradle-api:26.6.3
         project : > com.android.tools.build:gradle:3.6.3 > com.android.tools.build:gradle-api:3.6.3
         project : > com.android.tools.build:gradle:3.6.3 > androidx.databinding:databinding-compiler-common:3.6.3
         project : > com.android.tools.build:gradle:3.6.3 > com.android.tools.build:builder:3.6.3 > com.android.tools:common:26.6.3
         project : > com.android.tools.build:gradle:3.6.3 > com.android.tools.build:builder:3.6.3 > com.android.tools.analytics-library:tracker:26.6.3
```

I would suggest upgrading one item at a time and compile, to make sure it still works, before upgrading the next item.

**Comment by TacoTheDank** [comment]
I cut out the second commit.

**Comment by tobykurien** [comment]
To test your changes, you can run `./gradlew assembleDebug` from the command line in the project root directory.  This will ensure that you are testing the build configuration independent of any Eclipse or other IDE settings/issues.

If you do that, you'll see now that there's a new error, which may be related to the AndroidX stuff: `AAPT: Attribute "actionBarSize" already defined with incompatible format.` I think you can see now why I stuck with older versions that work :-) I'm not sure that there is any benefit to upgrading to AndroidX at this stage.

**Comment by TacoTheDank** [comment]
@tobykurien Oh god ok lol. I'll just do the deletion and glide updates then.

**Comment by TacoTheDank** [comment]
@tobykurien I couldn't even update Glide to 4, Studio was just throwing around all sorts of whack errors from things being wrongly undefined to other weird stuff. If you'd like to update Glide to 4 yourself (it's worth it though), here's the [migration guide](https://bumptech.github.io/glide/doc/migrating.html) and the [changelog](https://github.com/bumptech/glide/releases) (version 4.10.0 and up is AndroidX, so use 4.9.0).

**Pull request merged**
