### PR TITLE
Adding french translation

### PR DESCRIPTION
**Pull request by RyDroid**

### CODE REVIEW

**Comment by tobykurien** [comment]
Thank you!

**Comment by tobykurien** [comment]
I've added a few new strings as well as the arrays.xml file. Could you please translate these? I can make a new release once this is complete. Thanks!

**Comment by tobykurien** [comment]
@RyDroid please note I've moved the french translations into the /translations folder. Would be great if you could translate the new strings, then I can include it in the following release. Thanks :)

**Comment by RyDroid** [comment]
Done. https://github.com/tobykurien/WebApps/pull/23

**Comment by tobykurien** [comment]
Thanks!

**Comment by tobykurien** [comment]
@RyDroid there's also this file that needs translations (very small file): https://github.com/tobykurien/WebApps/blob/master/translations/values-fr/arrays.xml

**Comment by RyDroid** [comment]
French translation is finally finished! https://github.com/tobykurien/WebApps/pull/25

**Pull request merged**
