### PR TITLE
Create a new icon

### PR DESCRIPTION
**Pull request by TacoTheDank**
Here, I've replaced the old outdated holo icon with a new and improved custom-made snazzy adaptive sandbox icon! Hope you enjoy it!

I had to work around the perpetually failing Gradle builds from the weird setup you've got here. I hope you consider updating it so people who want to contribute don't run into Java wrong-version runtime errors and weird errors like `Caused by: org.gradle.internal.event.ListenerNotificationException: Failed to notify project evaluation listener` and `Unable to find method 'com.android.build.gradle.api.BaseVariant.getOutputs()Ljava/util/List;'`.

Anyway, here's how it looks.

ic_launcher-playstore
ic_launcher
ic_launcher_round

Original icon source (Creative Commons): https://thenounproject.com/term/sandbox/30514/
Shadow added with https://tibbi.github.io/AndroidAssetStudio/icons-launcher.html

Thanks!

### CODE REVIEW

**Comment by tobykurien** [comment]
Thank you for the contribution @TacoTheDank ! Sorry about the build issues, unfortunately the gradle plugin I use is sensitive to the JVM version, as you discovered.

I like the icon. I see that the license requires crediting the author or else purchasing a license. Would we have to credit the author in the app somewhere?

**Comment by tobykurien** [comment]
Just adding a reference also to another proposed icon: #141

**Comment by TacoTheDank** [comment]
@tobykurien Yeah, or you can also do it in the README. I'd suggest the README, so you don't have to code an about page for it. Maybe below the Development section would be good. Also you should add Glide and the Support libraries to the Libraries section.

I didn't even notice there'd been another issue for an icon, haha.

I'd like to try to do some other miscellaneous work on the app, so I hope there's a way to get the building to work. Maybe by forking the greensopinion library and updating stuff in it, and updating the plugins and fixing any deprecations that show up. Sucks that I can't seem to figure out how to get that to work, I've tried a bunch of different stuff. I use Android Studio, lol.

**Comment by tobykurien** [comment]
Have you setup as per the README? This app uses the Xtend plugin (see https://xtend-lang.org ). Since my laptop doesn't have the resources to run Android Studio, I'm now using Visual Studio Code and the `debug.sh` script to build and run on my device.

**Comment by TacoTheDank** [comment]
I'll try that out, then. I'll install VSCode (which honestly I don't much care for, maybe because I'm not used to it) and give it a shot.

**Comment by tobykurien** [comment]
VSCode is not a great dev experience for this project though (I just use it for the small maintenance tasks), because it doesn't support Xtend lang, so no code completion, etc. Best experience is actually Eclipse, as Xtend is fully supported there. This project actually pre-dates Android Studio.

**Comment by TacoTheDank** [comment]
@tobykurien I figured, lol.

**Pull request merged**
